### ISSUE TITLE
Dêem uma olhada

### ISSUE THREAD

**Issue by gabriel-lins-ds** [Lucasvor/PI-BOSTON#1]
https://pt.wikipedia.org/wiki/N%C3%BAmero_triangular
(Acho que seria bom se esse fosse o nível 8)

**Comment by Lucasvor** [comment]
é uma boa ideia, mas não é um pouco difícil para quem vai jogar ?

**Comment by gabriel-lins-ds** [comment]
Sim, por isso eu coloquei como último nível.

**Comment by RodrigoSaiki** [comment]
Boa ideia para ser o ultimo nível.
